import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Container } from '@/components/common/container';
import { Sidebar } from '@/components/layout/sidebar/index';
import { ClientOnly } from '@/components/layout/client-only';

export const metadata: Metadata = {
  title: '🟢 [Dashboard]',
  description: 'Generated by create next app',
};

export default function DashboardLayout({ children }: PropsWithChildren) {
  return (
    <ClientOnly>
      <div className='w-full pt-10 pb-[72px]'>
        <Container>
          <div className="flex lg:flex-row flex-col gap-8 lg:gap-[72px]">
            <div className="flex-[0_0_100%] max-w-full lg:flex-[0_0_16.5rem] lg:max-w-[16.5rem]">
              <Sidebar />
            </div>
            <div className="w-full">
              {children}
            </div>
          </div>
        </Container>
      </div>
    </ClientOnly>
  );
}
